config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  get 'home/index'

  devise_for :users
  #root 'posts#index'

  resources :essays
  resources :posts do
    resources :comments
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/essay.rb
class Essay < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def after_sign_in_path_for(user)
    posts_path
  end

  def after_sign_out_path_for(user)
    root_path
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find_by(id: params[:post_id])
    @comment = @post.comments.new(comment_params)
    if @comment.save
      flash[:notice] = 'Comment successfully saved'
      redirect_to post_path(@post.id)
    else
      flash[:notice] = 'Could not save the comment. Something went wrong'
      render 'new'
    end
  end


  private
  def comment_params
    params.require(:comment).permit(:body)
  end

end

app/controllers/essays_controller.rb
class EssaysController < ApplicationController
  before_action :set_essay, only: [:show, :edit, :update, :destroy]

  # GET /essays
  # GET /essays.json
  def index
    @essays = Essay.all
  end

  # GET /essays/1
  # GET /essays/1.json
  def show
  end

  # GET /essays/new
  def new
    @essay = Essay.new
  end

  # GET /essays/1/edit
  def edit
  end

  # POST /essays
  # POST /essays.json
  def create
    @essay = Essay.new(essay_params)

    respond_to do |format|
      if @essay.save
        format.html { redirect_to @essay, notice: 'Essay was successfully created.' }
        format.json { render :show, status: :created, location: @essay }
      else
        format.html { render :new }
        format.json { render json: @essay.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /essays/1
  # PATCH/PUT /essays/1.json
  def update
    respond_to do |format|
      if @essay.update(essay_params)
        format.html { redirect_to @essay, notice: 'Essay was successfully updated.' }
        format.json { render :show, status: :ok, location: @essay }
      else
        format.html { render :edit }
        format.json { render json: @essay.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /essays/1
  # DELETE /essays/1.json
  def destroy
    @essay.destroy
    respond_to do |format|
      format.html { redirect_to essays_url, notice: 'Essay was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_essay
      @essay = Essay.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def essay_params
      params.fetch(:essay, {})
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
  end

  def new
    @post = Post.new
  end

  def show
    @post = Post.find_by id: params[:id]
    @comment = Comment.new
  end

  def create
    @post = Post.new(posts_params)
    if @post.save
      flash[:notice] = 'You successfully created a post'
      redirect_to(action: 'show', id: @post.id)
    else
      flash[:notice] = 'Couldn\'t create a post. Something went wrong.'
      render 'new'
    end
  end



  private
  def posts_params
    params.require(:post).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/essays_helper.rb
module EssaysHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/essays/_form.html.erb
<%= form_for(essay) do |f| %>
  <% if essay.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(essay.errors.count, "error") %> prohibited this essay from being saved:</h2>

      <ul>
      <% essay.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/essays/edit.html.erb
<h1>Editing Essay</h1>

<%= render 'form', essay: @essay %>

<%= link_to 'Show', @essay %> |
<%= link_to 'Back', essays_path %>

app/views/essays/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Essays</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @essays.each do |essay| %>
      <tr>
        <td><%= link_to 'Show', essay %></td>
        <td><%= link_to 'Edit', edit_essay_path(essay) %></td>
        <td><%= link_to 'Destroy', essay, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Essay', new_essay_path %>

app/views/essays/new.html.erb
<h1>New Essay</h1>

<%= render 'form', essay: @essay %>

<%= link_to 'Back', essays_path %>

app/views/essays/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_essay_path(@essay) %> |
<%= link_to 'Back', essays_path %>

app/views/home/index.html.erb
<h1>Welcome to my Blog</h1>

<%= link_to "Sign In", new_user_session_path %>
<br>
<%= link_to "Sign Up", new_user_registration_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if user_signed_in? %>
      <%= link_to "Sign Out", destroy_user_session_path, method: :delete %> <br> <br>
    <% end %>

    <% if flash[:notice] %>
      <%= flash.each do |key, value|%>
        <div class= <%key%>> <%= value %> </div>
      <% end %>
    <% end %>

    <% if flash[:alert] %>
      <%= flash.each do |key, value|%>
        <div class= <%key%>> <%= value %> </div>
      <% end %>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<html>
  <body>
    <% Post.all.each do |post| %>
      <strong>Title:</strong> <%= post.title %> <br>
      <strong>Body:</strong> <%= post.body %> <br>
      <%= link_to "View", post_path(post) %>
      <br> <br>
    <% end %>
  </body>
</html>

app/views/posts/new.html.erb
<%= form_for(@post, url: posts_path) do |f| %>
  <%= f.label(:title) %>
  <%= f.text_field(:title) %>

  <%= f.label(:body) %>
  <%= f.text_area(:body) %>

  <%= f.submit %>
<% end %>

app/views/posts/show.html.erb
<strong>Title:</strong> <br>
<%= @post.title %>
<br> <br>
<strong>Body:</strong> <br>
<%= @post.body %> <br> <br>

<strong>Comments:</strong> <br>
<% @post.comments.all.each do |comment| %>
  <%= comment.body %> <br>
<% end %>
<br> <br>

<strong>New Comment:</strong> <br>
<%= form_for(@comment, url: post_comments_path(@post)) do |f| %>
  <%= f.text_area :body %> <br>
  <%= f.submit :submit %>
<% end %>